# Generated by Django 4.2 on 2026-02-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
